### ISSUE TITLE
Scala3 support

### ISSUE THREAD

**Issue by kurellajunior** [Jyllands-Posten/play-prometheus-filters#60]
Thanks for that. I was looking for exactly such thing to get the prometheus hotspot metics from my play server.
Do you have any experience with using this in scala 3?
```[tasklist]
### Tasks
- [x] upgrade sbt to use java21
- [x] integrate 2.13 lib into sbt
- [ ] add filters as described in Readme
- [x] activate prometheus jvm metrics
```

**Comment by SoerenSilkjaer** [comment]
@kurellajunior 

We have not upgraded any of the projects that use this dependency to Scala 3 yet, so we don't have any production experience with it.

**Comment by kurellajunior** [comment]
Then I will report here, if I can get it running (and how)

- adding `"io.github.jyllands-posten" % "play-prometheus-filters_2.13" % "1.0.1"` as library dependency worked
- The provided PrometheusController is not link compatible with play3 in scala 3. Copying it into my project solved that, as it is now compiled against scala3. Similar Problems are to be expected by other provided controllers.
- Skipped the filters for now

So all I use now is the WriterAdapter from that lib, which I probably can do myself too.
Seems, all I needed was your folks guidance on how to create a proper PrometheusController. I owe you one!
